# Generated by Django 4.1 on 2022-09-02 22:02

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=backend.models.generate_room_code, max_length=6, unique=True
            ),
        ),
    ]
