# Generated by Django 4.1 on 2022-08-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeammateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.user"
                    ),
                ),
                (
                    "teammate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teammate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="UserSkill",),
        migrations.AddField(
            model_name="skill",
            name="room",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.room",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="room",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.room",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="title",
            field=models.CharField(default="", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="story",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.story",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeline",
            name="room",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.room",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skill", name="name", field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="taskrequirement",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.skill"
            ),
        ),
        migrations.AddField(
            model_name="taskrequirement",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.task"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.task"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="teammate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.teammate"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="timeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.timeline"
            ),
        ),
    ]
