# Generated by Django 4.1 on 2022-09-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="admin",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
